logdir: 'log/'
seed_everything: 42

trainer:
  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args: 
      project: inference_learning
      dir: ${logdir}
      offline: false
  accelerator: 'cpu'
  devices: 1
  enable_checkpointing: false
  default_root_dir: ${logdir}
  max_epochs: 1  # Number of batches to train with
  log_every_n_steps: 200 # Logging every n batch
  val_check_interval: 1000 # Valid inteval

model:
  network: cnn
  method: strict
  gamma: 0.01
  inference_iter: 100
  init: pred
  loss_func:
    class_path: torch.nn.CrossEntropyLoss

optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 0.002
    weight_decay: 0
  
data:
  train_batch_size: 32
  val_batch_size: 256